import React from 'react';
import { db } from '@/lib/db';
import { settings } from '@/lib/db/schema';
import { eq } from 'drizzle-orm';
import { defaultStoreConfig } from '@/app/api/settings/route';
import { ShieldCheck, Scale, FileText, AlertCircle } from 'lucide-react';

export default async function TermsPage() {
  const record = await db.query.settings.findFirst({
    where: eq(settings.key, 'store_config'),
  });

  const config = record ? (record.value as any) : defaultStoreConfig;

  return (
    <div className="mx-auto max-w-4xl px-4 py-12 sm:px-6 lg:px-8 font-sans flex flex-col gap-8">
      
      {/* Title */}
      <div className="text-center flex flex-col items-center gap-3">
        <span className="text-[10px] font-black uppercase text-emerald-500 bg-emerald-50 px-3 py-1 rounded-full tracking-wide">
          Legal Compliance
        </span>
        <h1 className="text-2xl sm:text-3xl font-black text-zinc-900 dark:text-zinc-50 tracking-tight">
          Terms & Conditions of Service
        </h1>
        <p className="text-xs text-zinc-500">
          Last Updated: August 12, 2026 • Compliant under Information Technology Act, 2000 & Consumer Protection Rules, 2020
        </p>
      </div>

      <div className="rounded-2xl bg-amber-50/50 border border-amber-100 p-4 text-xs font-semibold text-amber-800 leading-normal flex gap-2.5 dark:bg-amber-950/20 dark:border-amber-900/30 dark:text-amber-400">
        <AlertCircle className="h-5 w-5 shrink-0 mt-0.5" />
        <div>
          <h4 className="font-extrabold uppercase text-[10px]">Electronic Contract Consent</h4>
          <p className="mt-1 leading-normal font-medium">
            This document is an electronic record generated by a computer system and does not require physical or digital signatures. This electronic record is published in accordance with the provisions of Rule 3 of the Information Technology (Intermediaries guidelines) Rules, 2011.
          </p>
        </div>
      </div>

      <div className="bg-white dark:bg-zinc-900 rounded-3xl p-6 sm:p-10 border border-zinc-100 dark:border-zinc-800 shadow-sm flex flex-col gap-6 text-xs sm:text-sm text-zinc-650 dark:text-zinc-350 leading-relaxed font-medium">
        
        <section className="flex flex-col gap-2">
          <h3 className="text-sm font-black text-zinc-900 dark:text-zinc-50 uppercase tracking-wider flex items-center gap-1.5 border-b border-zinc-50 dark:border-zinc-800 pb-2">
            <Scale className="h-4.5 w-4.5 text-emerald-500" />
            1. Corporate Identifiers & Regulatory Disclosures
          </h3>
          <p>
            The eCommerce platform is owned, managed, and operated by <strong>{config.companyName}</strong>, a corporate body registered under the Companies Act, 2013 in India.
          </p>
          <ul className="list-disc pl-6 flex flex-col gap-1.5 mt-2">
            <li><strong>Registered Address:</strong> {config.registeredAddress}</li>
            {config.cin && <li><strong>Corporate Identity Number (CIN):</strong> {config.cin}</li>}
            {config.gstin && <li><strong>GSTIN Registration:</strong> {config.gstin}</li>}
            <li><strong>Support Hotline:</strong> {config.supportPhone}</li>
            <li><strong>Compliance Email:</strong> {config.supportEmail}</li>
          </ul>
        </section>

        <section className="flex flex-col gap-2 mt-4">
          <h3 className="text-sm font-black text-zinc-900 dark:text-zinc-50 uppercase tracking-wider flex items-center gap-1.5 border-b border-zinc-50 dark:border-zinc-800 pb-2">
            <FileText className="h-4.5 w-4.5 text-emerald-500" />
            2. Electronic Contract Formation (Section 10A of IT Act, 2000)
          </h3>
          <p>
            By placing an order on E-Market PWA website, you offer to purchase products. Clicking "Place Order" constitutes legal execution of an electronic contract. E-Market reserves the right to accept or decline the contract depending on:
          </p>
          <ul className="list-disc pl-6 flex flex-col gap-1.5 mt-1.5">
            <li><strong>Inventory Stock validation:</strong> Products are subject to stock Availability checks in real-time.</li>
            <li><strong>Verification of customer details:</strong> Verification of address and mobile contact numbers.</li>
            <li><strong>Operational boundary limits:</strong> Orders must fall within serviced areas: <strong>{config.locations.join(', ')}</strong>.</li>
          </ul>
        </section>

        <section className="flex flex-col gap-2 mt-4">
          <h3 className="text-sm font-black text-zinc-900 dark:text-zinc-50 uppercase tracking-wider flex items-center gap-1.5 border-b border-zinc-50 dark:border-zinc-800 pb-2">
            <ShieldCheck className="h-4.5 w-4.5 text-emerald-500" />
            3. Pricing & FSSAI Food Safety Warranties
          </h3>
          <p>
            For variable weight products (fresh chicken, meat, fish, vegetables), final packed quantities might vary by ±10%. Billing will be adjusted based on the actual weight recorded in our transaction ledgers at dispatch. The customer agrees to pay the adjusted sum as shown in their final invoice receipt.
          </p>
          <p className="mt-2">
            All prices are in Indian Rupees (INR) and include GST, tech fees, and packaging charges as detailed during checkout. All food articles are handled in compliance with FSSAI standards.
          </p>
        </section>

        <section className="flex flex-col gap-2 mt-4">
          <h3 className="text-sm font-black text-zinc-900 dark:text-zinc-50 uppercase tracking-wider flex items-center gap-1.5 border-b border-zinc-50 dark:border-zinc-800 pb-2">
            4. Grievance Redressal Mechanism (eCommerce Rules, 2020)
          </h3>
          <p>
            In accordance with Consumer Protection Rules, we have appointed a Grievance Redressal Officer to resolve user disputes:
          </p>
          <div className="bg-zinc-50/50 dark:bg-zinc-950/20 p-4 rounded-xl border border-zinc-100 dark:border-zinc-850 flex flex-col gap-1.5 mt-2">
            <div className="flex justify-between">
              <span className="font-bold text-zinc-500 text-[10px]">Officer Name:</span>
              <span className="font-extrabold text-zinc-900 dark:text-zinc-100">{config.grievanceOfficerName}</span>
            </div>
            <div className="flex justify-between">
              <span className="font-bold text-zinc-500 text-[10px]">Official Email ID:</span>
              <span className="font-bold text-emerald-500">{config.grievanceOfficerEmail}</span>
            </div>
            <div className="flex justify-between">
              <span className="font-bold text-zinc-500 text-[10px]">Timeline to Respond:</span>
              <span className="font-bold text-zinc-850 dark:text-zinc-200">Acknowledge within 48h, Resolve within 30 days</span>
            </div>
          </div>
        </section>

      </div>

    </div>
  );
}
